module.exports = {
	"combine_nested_dirname": true,
	"fopen_flag_order": false,
	"fopen_flags": true,
	"function_declaration": true,
	"function_typehint_space": true,
	"implode_call": true,
	"lambda_not_used_import": true,
	"method_argument_space": true,
	"no_spaces_after_function_name": true,
	"no_unreachable_default_argument_value": true,
	"no_useless_sprintf": true,
	"nullable_type_declaration_for_default_null_value": { "use_nullable_type_declaration": false },
	"phpdoc_to_param_type": false,
	"phpdoc_to_property_type": false,
	"phpdoc_to_return_type": false,
	"regular_callable_call": true,
	"return_type_declaration": false,
	"single_line_throw": true,
	"static_lambda": true,
	"use_arrow_functions": true,
	"void_return": false
};